# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-04 02:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180304_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 2, 28, 1, 545458, tzinfo=utc)),
        ),
    ]
